[general]

# Default colors
[colors.primary]
background = '#061923'
foreground = '#e5c49e'

[colors.cursor]
text = '#061822'
cursor = '#feaf3c'

[colors.selection]
text = '#ffe9d7'
background = '#265b75'

# Normal colors
[colors.normal]
black = '#1d485f'
red = '#db662d'
green = '#008eab'
yellow = '#feaf3c'
blue = '#255a62'
magenta = '#77dbf4'
cyan = '#5fb1c2'
white = '#c0ffee'

# Bright colors
[colors.bright]
black = '#545d65'
red = '#dd998a'
green = '#739da8'
yellow = '#fedaae'
blue = '#0bc7e3'
magenta = '#c6e8f1'
cyan = '#97b9c0'
white = '#c0ffee'

[font]
size = 15.0

[font.bold]
family = "Monospace"
style = "Bold"

[font.bold_italic]
family = "Monospacee"
style = "Bold Italic"

[font.italic]
family = "Monospace"
style = "Italic"

[font.normal]
family = "Monospace"
style = "Bold"


[window]
opacity = 0.25


