require('config.options')
require('config.plugins')
require('config.telescope')
require('config.lsp')
require('config.treesitter')
require('config.nvim-cmp')
require('config.lualine')
require('config.keymaps')
